name: Update IP List

on:
  schedule:
    - cron: '0 */6 * * *' # 每6小时运行一次 (如果你需要3小时, 改为 '0 */3 * * *')
  workflow_dispatch: # 允许手动触发

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 2
        keep_minimum_runs: 6
        
    - name: Run script
      run: python ${{ github.workspace }}/collect_ips.py # 确保你的python脚本文件名与这里一致
      
    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Action"
        git config --global pull.rebase false
        git pull # 拉取远程更改，避免冲突
        if [ -n "$(git status --porcelain)" ]; then
          git add ip.txt nodes.txt sub.txt  # <-- 关键修改在这里
          git commit -m "Automatic IP and subscription update"
          git push
        else
          echo "No changes detected, skipping commit."
        fi
